# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 28) do

  create_table "custom_views", :force => true do |t|
    t.column "name",            :string
    t.column "user_id",         :integer
    t.column "list_id",         :integer
    t.column "limit",           :string
    t.column "old_id",          :integer
    t.column "view_parameters", :string
  end

  create_table "document_versions", :force => true do |t|
    t.column "document_id",        :integer
    t.column "version",            :integer
    t.column "name",               :string
    t.column "body",               :text
    t.column "html",               :text
    t.column "updated_at",         :datetime
    t.column "user_id",            :integer
    t.column "administrator_only", :string
  end

  create_table "documents", :force => true do |t|
    t.column "name",               :string
    t.column "body",               :text
    t.column "html",               :text
    t.column "version",            :integer
    t.column "user_id",            :integer
    t.column "administrator_only", :boolean
  end

  add_index "documents", ["name"], :name => "index_documents_on_name"

  create_table "email_subscriptions", :force => true do |t|
    t.column "user_id", :integer
    t.column "list_id", :integer
  end

  add_index "email_subscriptions", ["user_id"], :name => "index_email_subscriptions_on_user_id"
  add_index "email_subscriptions", ["list_id"], :name => "index_email_subscriptions_on_list_id"

  create_table "images", :force => true do |t|
    t.column "data",       :binary
    t.column "created_at", :datetime
  end

  create_table "list_lists", :force => true do |t|
    t.column "list_id",    :integer
    t.column "child_id",   :integer
    t.column "dependency", :string
  end

  add_index "list_lists", ["list_id"], :name => "index_list_lists_on_list_id"
  add_index "list_lists", ["child_id"], :name => "index_list_lists_on_child_id"

  create_table "list_talks", :force => true do |t|
    t.column "list_id",    :integer
    t.column "talk_id",    :integer
    t.column "dependency", :string
  end

  add_index "list_talks", ["list_id"], :name => "index_list_talks_on_list_id"
  add_index "list_talks", ["talk_id"], :name => "index_list_talks_on_talk_id"

  create_table "list_users", :force => true do |t|
    t.column "list_id", :integer
    t.column "user_id", :integer
  end

  add_index "list_users", ["list_id"], :name => "index_lists_users_on_list_id"
  add_index "list_users", ["user_id"], :name => "index_lists_users_on_user_id"

  create_table "lists", :force => true do |t|
    t.column "name",             :string
    t.column "details",          :text
    t.column "type",             :string,   :limit => 50
    t.column "details_filtered", :text
    t.column "ex_directory",     :boolean,                :default => false
    t.column "old_id",           :integer
    t.column "image_id",         :integer
    t.column "created_at",       :datetime
    t.column "updated_at",       :datetime
  end

  add_index "lists", ["name"], :name => "index_lists_on_name"
  add_index "lists", ["ex_directory"], :name => "index_lists_on_ex_directory"

  create_table "related_lists", :force => true do |t|
    t.column "related_id",   :integer
    t.column "related_type", :string
    t.column "list_id",      :integer
    t.column "score",        :float
  end

  add_index "related_lists", ["related_id", "related_type"], :name => "index_related_lists_on_related_id_and_related_type"
  add_index "related_lists", ["list_id"], :name => "index_related_lists_on_list_id"
  add_index "related_lists", ["score"], :name => "index_related_lists_on_score"

  create_table "related_talks", :force => true do |t|
    t.column "related_id",   :integer
    t.column "related_type", :string
    t.column "talk_id",      :integer
    t.column "score",        :float
  end

  add_index "related_talks", ["related_id", "related_type"], :name => "index_related_talks_on_related_id_and_related_type"
  add_index "related_talks", ["talk_id"], :name => "index_related_talks_on_talk_id"
  add_index "related_talks", ["score"], :name => "index_related_talks_on_score"

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"

  create_table "talks", :force => true do |t|
    t.column "title",             :string,   :default => ""
    t.column "abstract",          :text
    t.column "special_message",   :string
    t.column "start_time",        :datetime
    t.column "end_time",          :datetime
    t.column "name_of_speaker",   :string
    t.column "speaker_id",        :integer
    t.column "series_id",         :integer
    t.column "venue_id",          :integer
    t.column "created_at",        :datetime
    t.column "updated_at",        :datetime
    t.column "abstract_filtered", :text
    t.column "organiser_id",      :integer
    t.column "old_id",            :integer
    t.column "ex_directory",      :boolean,  :default => false
    t.column "image_id",          :integer
  end

  add_index "talks", ["start_time"], :name => "index_talks_on_start_time"
  add_index "talks", ["end_time"], :name => "index_talks_on_end_time"
  add_index "talks", ["series_id"], :name => "index_talks_on_series_id"
  add_index "talks", ["speaker_id"], :name => "index_talks_on_speaker_id"
  add_index "talks", ["organiser_id"], :name => "index_talks_on_organiser_id"

  create_table "tickles", :force => true do |t|
    t.column "created_at",      :datetime
    t.column "about_id",        :integer
    t.column "about_type",      :string
    t.column "sender_id",       :integer
    t.column "recipient_email", :text
    t.column "sender_email",    :string
    t.column "sender_name",     :string
    t.column "sender_ip",       :string
  end

  create_table "users", :force => true do |t|
    t.column "email",              :string
    t.column "name",               :string
    t.column "password",           :string,   :limit => 50
    t.column "affiliation",        :string,   :limit => 75
    t.column "administrator",      :integer,  :limit => 50, :default => 0,    :null => false
    t.column "old_id",             :integer
    t.column "last_login",         :datetime
    t.column "crsid",              :string
    t.column "image_id",           :integer
    t.column "name_in_sort_order", :string
    t.column "ex_directory",       :boolean,                :default => true
    t.column "created_at",         :time
    t.column "updated_at",         :time
  end

  add_index "users", ["email"], :name => "index_users_on_email"
  add_index "users", ["crsid"], :name => "index_users_on_crsid"
  add_index "users", ["name_in_sort_order"], :name => "index_users_on_name_in_sort_order"

end
